/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author niree
 */
public class admindashboardd extends javax.swing.JFrame {

    /**
     * Creates new form admindashboardd
     */
    public admindashboardd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parcelmanagement = new javax.swing.JButton();
        deliveryagent = new javax.swing.JButton();
        warehouse = new javax.swing.JButton();
        tracking = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BACK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parcelmanagement.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        parcelmanagement.setText("PARCEL MANAGEMENT");
        parcelmanagement.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        parcelmanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcelmanagementActionPerformed(evt);
            }
        });
        getContentPane().add(parcelmanagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 21));

        deliveryagent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deliveryagent.setText("DELIVERY AGENT");
        deliveryagent.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        deliveryagent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryagentActionPerformed(evt);
            }
        });
        getContentPane().add(deliveryagent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 165, 21));

        warehouse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        warehouse.setText("WAREHOUSE");
        warehouse.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        warehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warehouseActionPerformed(evt);
            }
        });
        getContentPane().add(warehouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 165, 21));

        tracking.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tracking.setText("TRACKING");
        tracking.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        tracking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackingActionPerformed(evt);
            }
        });
        getContentPane().add(tracking, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 170, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ADMIN DASHBOARD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 19, -1, -1));

        BACK.setBackground(new java.awt.Color(55, 55, 55));
        BACK.setForeground(new java.awt.Color(252, 230, 148));
        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        getContentPane().add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 268, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gradient-Colors-4.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parcelmanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcelmanagementActionPerformed
        parcelmain pm= new parcelmain();
        pm.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_parcelmanagementActionPerformed

    private void deliveryagentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryagentActionPerformed
        deliveryagent da =new deliveryagent();
        da.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_deliveryagentActionPerformed

    private void warehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warehouseActionPerformed
        warehouse wh = new warehouse();
        wh.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_warehouseActionPerformed

    private void trackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackingActionPerformed
       tracking tc=new tracking();
       tc.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_trackingActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        // TODO add your handling code here:
         main cy=new main();
       cy.setVisible(true);
    }//GEN-LAST:event_BACKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admindashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admindashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admindashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admindashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admindashboardd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton deliveryagent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton parcelmanagement;
    private javax.swing.JButton tracking;
    private javax.swing.JButton warehouse;
    // End of variables declaration//GEN-END:variables
}
