
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author niree
 */
public class admintrackinginfo extends javax.swing.JFrame {

    /**
     * Creates new form admintrackinginfo
     */
    public admintrackinginfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabletracking = new javax.swing.JTable();
        trackinginfo = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        FETCH = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabletracking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TRACKING ID", "PARCEL ID", "TIME STAMP", "LOCATION", "STATUS"
            }
        ));
        jScrollPane1.setViewportView(tabletracking);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 40, 396, 255));

        trackinginfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        trackinginfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trackinginfo.setText("TRACKING INFO");
        getContentPane().add(trackinginfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 6, 186, 22));

        back.setBackground(new java.awt.Color(55, 55, 55));
        back.setForeground(new java.awt.Color(252, 230, 148));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 305, -1, -1));

        FETCH.setBackground(new java.awt.Color(55, 55, 55));
        FETCH.setForeground(new java.awt.Color(252, 230, 148));
        FETCH.setText("FETCH");
        FETCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FETCHActionPerformed(evt);
            }
        });
        getContentPane().add(FETCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 305, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gradient-Colors-4.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        tracking add =new tracking();
        add.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void FETCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FETCHActionPerformed
        String url="jdbc:mysql://localhost:3306/parcel";
    String user="root";
    String pwd="mr.pal2712";
    
    String query="SELECT * FROM TRACKING;";
    ResultSet r=null;
   Statement st=null;
    DefaultTableModel dm=(DefaultTableModel)tabletracking.getModel();
    
    
    try{
    Connection con=DriverManager.getConnection(url,user,pwd);
     st=con.createStatement();
    r=st.executeQuery(query);
    while(r.next()){
        String agid=r.getString("TRACKING_ID");
        String name=r.getString("PARCEL_ID");
        String cinfo=r.getString("TIMESTAMP");
        String vinfo=r.getString("LOCATION");
        String route=r.getString("STATUS");
        dm.addRow(new Object [] {agid,name,cinfo,vinfo,route});
}
    
    }catch(SQLException e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    
    }// TODO add your handling code here:
    }//GEN-LAST:event_FETCHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admintrackinginfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admintrackinginfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admintrackinginfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admintrackinginfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admintrackinginfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FETCH;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabletracking;
    private javax.swing.JLabel trackinginfo;
    // End of variables declaration//GEN-END:variables
}
