/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author niree
 */
public class deliveryagent extends javax.swing.JFrame {

    /**
     * Creates new form deliveryagent
     */
    public deliveryagent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deliveryagent = new javax.swing.JLabel();
        createdeliveryagent = new javax.swing.JButton();
        deliveryagentinfo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deliveryagent.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deliveryagent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deliveryagent.setText("DELIVERY AGENT");
        getContentPane().add(deliveryagent, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 19, 175, 24));

        createdeliveryagent.setBackground(new java.awt.Color(55, 55, 55));
        createdeliveryagent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        createdeliveryagent.setForeground(new java.awt.Color(252, 230, 148));
        createdeliveryagent.setText("CREATE DELIVERY AGENT");
        createdeliveryagent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createdeliveryagentActionPerformed(evt);
            }
        });
        getContentPane().add(createdeliveryagent, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 134, -1, 33));

        deliveryagentinfo.setBackground(new java.awt.Color(55, 55, 55));
        deliveryagentinfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deliveryagentinfo.setForeground(new java.awt.Color(252, 230, 148));
        deliveryagentinfo.setText("DELIVERY AGENT INFO");
        deliveryagentinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryagentinfoActionPerformed(evt);
            }
        });
        getContentPane().add(deliveryagentinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 134, -1, 33));

        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gradient-Colors-4.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createdeliveryagentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createdeliveryagentActionPerformed
        deliverycreateadmin ad =new deliverycreateadmin();
        ad.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_createdeliveryagentActionPerformed

    private void deliveryagentinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryagentinfoActionPerformed
        deliveryinfoadmin dai=new deliveryinfoadmin();
        dai.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_deliveryagentinfoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              admindashboardd add=new admindashboardd();
              add.setVisible(true);
              this.dispose();
  
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deliveryagent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deliveryagent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deliveryagent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deliveryagent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deliveryagent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createdeliveryagent;
    private javax.swing.JLabel deliveryagent;
    private javax.swing.JButton deliveryagentinfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
