
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author niree
 */
public class deliveryinfoadmin extends javax.swing.JFrame {

    /**
     * Creates new form deliveryinfoadmin
     */
    public deliveryinfoadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DELIVERYAGENTTABLE = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BACK = new javax.swing.JButton();
        Fetch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DELIVERYAGENTTABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AGENT ID", "NAME", "CONTACT INFO", "VECHILE INFO"
            }
        ));
        jScrollPane1.setViewportView(DELIVERYAGENTTABLE);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 31, 335, 239));

        jLabel1.setText("DELIVERY AGENT INFO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 9, 135, -1));

        BACK.setBackground(new java.awt.Color(55, 55, 55));
        BACK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BACK.setForeground(new java.awt.Color(252, 230, 148));
        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        getContentPane().add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 277, -1, -1));

        Fetch.setBackground(new java.awt.Color(55, 55, 55));
        Fetch.setForeground(new java.awt.Color(252, 230, 148));
        Fetch.setText("FETCH");
        Fetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FetchActionPerformed(evt);
            }
        });
        getContentPane().add(Fetch, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 277, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gradient-Colors-4.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        deliveryagent da =new deliveryagent();
        da.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_BACKActionPerformed

    private void FetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FetchActionPerformed
         String url="jdbc:mysql://localhost:3306/parcel";
    String user="root";
    String pwd="mr.pal2712";
    
    String query="SELECT * FROM DELIVERY_AGENT;";
    ResultSet r=null;
   Statement st=null;
    DefaultTableModel dm=(DefaultTableModel)DELIVERYAGENTTABLE.getModel();
    
    
    try{
    Connection con=DriverManager.getConnection(url,user,pwd);
     st=con.createStatement();
    r=st.executeQuery(query);
    while(r.next()){
        String agid=r.getString("AGENT_ID");
        String name=r.getString("NAME");
        String cinfo=r.getString("CONTACT_INFO");
        String vinfo=r.getString("VEHICAL_INFO");
        dm.addRow(new Object [] {agid,name,cinfo,vinfo});
        
        
        
    
        
    }
    
    }catch(SQLException e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    
    } // TODO add your handling code here:
    }//GEN-LAST:event_FetchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deliveryinfoadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deliveryinfoadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deliveryinfoadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deliveryinfoadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deliveryinfoadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JTable DELIVERYAGENTTABLE;
    private javax.swing.JButton Fetch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
