/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author niree
 */
public class parcelmain extends javax.swing.JFrame {

    /**
     * Creates new form parcelmain
     */
    public parcelmain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        parcelinfo = new javax.swing.JButton();
        createparcel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PARCEL ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 28, 101, -1));

        parcelinfo.setBackground(new java.awt.Color(55, 55, 55));
        parcelinfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        parcelinfo.setForeground(new java.awt.Color(252, 230, 148));
        parcelinfo.setText("PARCEL INFO");
        parcelinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcelinfoActionPerformed(evt);
            }
        });
        getContentPane().add(parcelinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 112, -1, 34));

        createparcel.setBackground(new java.awt.Color(55, 55, 55));
        createparcel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        createparcel.setForeground(new java.awt.Color(252, 230, 148));
        createparcel.setText("CREATE PARCEL");
        createparcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createparcelActionPerformed(evt);
            }
        });
        getContentPane().add(createparcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 112, -1, 34));

        jButton1.setBackground(new java.awt.Color(55, 55, 55));
        jButton1.setForeground(new java.awt.Color(252, 230, 148));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 239, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gradient-Colors-4.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parcelinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcelinfoActionPerformed

        adminparcelinfo admp=new adminparcelinfo();
        admp.setVisible(true);
        
            // TODO add your handling code here:
    }//GEN-LAST:event_parcelinfoActionPerformed

    private void createparcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createparcelActionPerformed
      parcelcreate pc= new parcelcreate();
      pc.setVisible(true);
      this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_createparcelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        admindashboardd cy=new admindashboardd();
        cy.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(parcelmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(parcelmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(parcelmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(parcelmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new parcelmain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createparcel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton parcelinfo;
    // End of variables declaration//GEN-END:variables
}
