
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author niree
 */
public class warehousecreate extends javax.swing.JFrame {

    /**
     * Creates new form delieveryinfoadmin
     */
    public warehousecreate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        warehouseid = new javax.swing.JLabel();
        capacity = new javax.swing.JLabel();
        inventory = new javax.swing.JLabel();
        loc = new javax.swing.JTextField();
        warehouse = new javax.swing.JTextField();
        cap = new javax.swing.JTextField();
        inven = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        BACK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CREATE WAREHOUSE INFO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 28, -1, -1));

        location.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        location.setText("LOCATION");
        getContentPane().add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 138, 97, 25));

        warehouseid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        warehouseid.setText("WAREHOUSE ID");
        getContentPane().add(warehouseid, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 97, 97, 25));

        capacity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        capacity.setText("CAPACITY");
        getContentPane().add(capacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 181, 97, 25));

        inventory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inventory.setText("INVENTORY");
        getContentPane().add(inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 224, 97, 25));

        loc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locActionPerformed(evt);
            }
        });
        getContentPane().add(loc, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 138, 167, 25));

        warehouse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        warehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warehouseActionPerformed(evt);
            }
        });
        getContentPane().add(warehouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 97, 167, 25));

        cap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capActionPerformed(evt);
            }
        });
        getContentPane().add(cap, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 181, 167, 25));

        inven.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invenActionPerformed(evt);
            }
        });
        getContentPane().add(inven, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 232, 167, 25));

        jButton1.setBackground(new java.awt.Color(55, 55, 55));
        jButton1.setForeground(new java.awt.Color(252, 230, 148));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 275, -1, -1));

        BACK.setBackground(new java.awt.Color(55, 55, 55));
        BACK.setForeground(new java.awt.Color(252, 230, 148));
        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        getContentPane().add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gradient-Colors-4.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void locActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locActionPerformed

    private void warehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warehouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warehouseActionPerformed

    private void capActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capActionPerformed

    private void invenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String url = "jdbc:mysql://localhost/parcel";
    String mysqluser = "root";
    String mysqlpwd = "mr.pal2712";
    String wid = warehouse.getText();
    String location = loc.getText();
    String capacity=cap.getText();
    String inventory=inven.getText();

    
    String query = "INSERT INTO WAREHOUSE VALUES(?,?,?,?)";
    
    try {
        Connection conn = DriverManager.getConnection(url, mysqluser, mysqlpwd);
        
        // Retrieve the current value of the counter from the database
        Statement stmt = conn.createStatement();
        
        // Prepare the insert statement
        PreparedStatement stm = conn.prepareStatement(query);
        stm.setString(1, wid);
        stm.setString(2, location);
        stm.setString(3, capacity);
        stm.setString(4, inventory);
        
        stm.execute();
        JOptionPane.showMessageDialog(this, "warehouse added");
        warehouse.setText(null);
            loc.setText(null);
            cap.setText(null);
            inven.setText(null);
            warehouse pm =new warehouse();
            pm.setVisible(true);
            this.dispose();
            
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        // TODO add your handling code here:
         warehouse cy=new warehouse();
       cy.setVisible(true);
    }//GEN-LAST:event_BACKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(warehousecreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(warehousecreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(warehousecreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(warehousecreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new warehousecreate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JTextField cap;
    private javax.swing.JLabel capacity;
    private javax.swing.JTextField inven;
    private javax.swing.JLabel inventory;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField loc;
    private javax.swing.JLabel location;
    private javax.swing.JTextField warehouse;
    private javax.swing.JLabel warehouseid;
    // End of variables declaration//GEN-END:variables
}
